name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Workaround for https://github.com/dotnet/format/issues/1805
  DOTNET_INSTALL_DIR: .temp/dotnet
  DOTNET_ROOT: .temp/dotnet

jobs:
  test:
    name: Test on '${{ matrix.platform }}'
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: .NET Setup
        uses: zyactions/dotnet-setup@v1
        with:
          global-json-file: test/global.json

      - name: .NET Restore
        uses: zyactions/dotnet-restore@v1
        with:
          workspace: test

      - name: .NET Format
        uses: ./
        with:
          workspace: test

      - name: .NET Format Project
        uses: ./
        with:
          workspace: test/Test.csproj
